### ISSUE TITLE
How do I train and test?

### ISSUE THREAD

**Issue by wjxxyz** [matheusbarrosp/sr-semseg-end2end#2]
I didn't find the training instructions, can you enrich the information on your page?

**Comment by matheusbarrosp** [comment]
Hello. I have updated the repository readme with the information regarding how to run the code and how to organize the training/testing dataset folder. I hope this helps solving your problems. If you find any wrong information, please let me know, as it has been some time since I last worked with this code. 
Thank you for reaching out.
